### ISSUE TITLE
Running Failure of Setup.py File

### ISSUE THREAD

**Issue by fukexue** [wilsonkl/SfM_Init#9] opened 2019-08-05 14:43 UTC
Hello, I want to ask about the expression of "library_dirs= []" in "setup.py". Do I need to fill in the appropriate folder name when I run on my own computer? Is the content in parentheses about the name of the folder where the lib and inclined files of Ceres are located?

**Comment by wilsonkl** [comment] 2019-08-05 18:09
Hello @fukexue , 
I don't want to go too far down the rabbit hole debugging build issues, but here's a quick answer. 

The Minimum Feedback Arc Set solver doesn't have any dependencies, so you won't need to provide any hints there for lib locations.

The second block in setup.py, (the translations solver) needs to link against ceres. So it needs to be able to find the ceres include headers and lib files. (Also, ceres itself dynamically links to some others: glog, gflag, suite-sparse, openmp, etc). Those need to be found too.

If you've installed these libs in their usual locations (on *nix systems---I don't know much about Windows compilation) then no further hints should be needed to find them.

If those libs are in places that aren't on the usual lib search path, you could add a hint to that line you mentioned.

**Comment by fukexue** [comment] 2019-08-10 03:52
thank you. When I compiled theSetup.py file,  the following error occurred.
There is no member variable defined in the ceres library for errors.
```
sfminit/src/trans_solver.cc: In function ‘void solve_translations_problem(const int*, const double*, const double*, int, double, double*, double, double, int)’:
sfminit/src/trans_solver.cc:66:13: error: ‘struct ceres::Solver::Options’ has no member named ‘num_linear_solver_threads’; did you mean ‘linear_solver_type’?
     options.num_linear_solver_threads = 16;
             ^~~~~~~~~~~~~~~~~~~~~~~~~
             linear_solver_type
error: command 'gcc' failed with exit status 1
```

**Comment by fukexue** [comment] 2019-08-11 06:00
What version of ceres-solver do you use?

**Comment by wilsonkl** [comment] 2019-08-12 13:02
Hi @fukexue,
It looks like the problem is that num_linear_solver_threads was deprecated in ceres-solver 2.0. I just committed a one-line patch to remove the reference.

**Comment by erupnik** [comment] 2019-08-19 14:02
Hello, 
thank you for sharing this code with the community. I'm having troubles running the example code in eccv_demo.py  

I keep on getting this error:
Traceback (most recent call last):
  File "scripts/eccv_demo.py", line 6, in <module>
    import sfminit
  File "SfM_Init/sfminit/__init__.py", line 11, in <module>
    from .transproblem import TransProblem
  File "SfM_Init/sfminit/transproblem.py", line 7, in <module>
    from ._wrapper_transsolver import solve_trans_problem
ImportError: SfM_Init/sfminit/_wrapper_transsolver.so: undefined symbol: cs_di_chol

Do you have any idea what could go wrong? I changed the respective paths in setup.py to make sure they point to my suitesparse....

thanks,

**Comment by wilsonkl** [comment] 2019-08-19 21:08
It looks like a linking problem. From a quick search, it looks like cs_di_chol is a symbol for CXSparse, which is an optional dependency for ceres-solver. Does this [post](https://groups.google.com/forum/#!topic/ceres-solver/YqE--RLOtjk) apply?

**Comment by erupnik** [comment] 2019-08-20 18:01
Yes, the post does apply. Thank you so much! I recompiled ceres as a shared library, then copied  libceres.so* to my anaconda lib directory. It worked beautifully until rotsolver where I discovered octave was not enough to call the m files. But that's another story.
Thanks again!

**Closed** 2020-03-17 00:19 UTC

**Comment by salahkhan94** [comment] 2020-09-15 17:03
> Yes, the post does apply. Thank you so much! I recompiled ceres as a shared library, then copied libceres.so* to my anaconda lib directory. It worked beautifully until rotsolver where I discovered octave was not enough to call the m files. But that's another story.
> Thanks again!
I'm compiling the Sfminit for python3, I've re-installed ceres as a shared library and specifically added paths to the location of generated .so files in the setup.py file but I continue to get the same error.
Here's where the ceres library got installed 
-- Installing: /usr/local/lib/cmake/Ceres/CeresTargets-release.cmake
-- Installing: /usr/local/lib/cmake/Ceres/CeresConfig.cmake
-- Installing: /usr/local/lib/cmake/Ceres/CeresConfigVersion.cmake
-- Up-to-date: /usr/local/lib/cmake/Ceres/FindGlog.cmake
-- Installing: /usr/local/lib/libceres.so.2.0.0
-- Installing: /usr/local/lib/libceres.so.2
-- Installing: /usr/local/lib/libceres.so

This is where cxsparse libs are:
/usr/lib/x86_64-linux-gnu/libcxsparse.a
/usr/lib/x86_64-linux-gnu/libcxsparse.so
/usr/lib/x86_64-linux-gnu/libcxsparse.so.3
/usr/lib/x86_64-linux-gnu/libcxsparse.so.3.2.0

here's what my setup.py looks like:
def get_transsolver_extension(config):

	sourcefiles        = ['sfminit/src/_wrapper_transsolver.pyx', 'sfminit/src/trans_solver.cc']
	include_dirs       = [config['eigen']] +  config['python_includes']
	library_dirs       = ['/usr/local/lib/', '/usr/lib/x86_64-linux-gnu']
	suite_sparse_libs  = ['lapack', 'ccolamd', 'spqr', 'cholmod', 'colamd','camd', 'amd', 'suitesparseconfig', 'cxsparse']
	ceres_libs         = ['ceres', 'glog', 'gflags']
	libraries          = ceres_libs + suite_sparse_libs + ['pthread', 'm'] + config['omp_libs']
	extra_compile_args = ['-O2', '-Wno-unused-function'] + config['omp_flags']
	define_macros      = []
	header_files       = ['trans_solver.h']

	return Extension("_wrapper_transsolver", sourcefiles,
		                    include_dirs=include_dirs,
		                    library_dirs=library_dirs,
		                    libraries=libraries,
		                    extra_compile_args=extra_compile_args,
		                    define_macros=define_macros,
		                    depends=header_files,
		                    language='c++')


can you please share what additional paths you've added in the setup.py file, I'd appreciate any help to resolve this

**Comment by salahkhan94** [comment] 2020-09-16 14:15
I was able to resolve the problem by linking the libceres.so file :
 
sudo ln -s /usr/local/lib/libceres.so /usr/lib/libceres.so
